### ISSUE TITLE
Code Review for Team 108(The Mambas)

### ISSUE THREAD

**Issue by ebeagusamuel** [ozovalihasan/bubble-sort#2]
- Use size instead of length
- Optimize the loop
- Check for rubocop errors

**Comment by SpaYco** [comment]
> Use size instead of length

why?

**Comment by ozovalihasan** [comment]
Thanks for your feedback. The optimization is done. Errors found by rubocop are fixed. But, 'length' is not changed with 'size' because any reasonable explanation to do this is not found, yet. Have a good day.
