### ISSUE TITLE
the herons review 

### ISSUE THREAD

**Issue by SpaYco** [ozovalihasan/bubble-sort#3]
good job with your code, everything works fine 

the only problem is that your code is not returning the array at the end, which makes it look that the code isn't working in the first place,  add that and everything will be 10/10

**Comment by ozovalihasan** [comment]
Thanks for your feedback. You are right. Methods are working correctly but they are not returning correct results. Now, it is fixed. More, we added one more optimization, so if you want, you may check it. Have a good day ...
